# Generated by Django 3.1.3 on 2021-02-07 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('weather', models.CharField(max_length=80, null=True)),
                ('mood', models.CharField(max_length=80, null=True)),
                ('wake_up', models.DateTimeField(null=True)),
                ('did_well', models.CharField(max_length=100, null=True)),
                ('happiness', models.TextField(max_length=100, null=True)),
                ('breakfast', models.CharField(max_length=100, null=True)),
                ('lunch', models.CharField(max_length=100, null=True)),
                ('dinner', models.CharField(max_length=100, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
