# Generated by Django 3.1.3 on 2021-02-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(choices=[('rainy', 'images/rainy'), ('cloudy', 'images/cloudy'), ('sunny', 'images/sunny'), ('snowy', 'images/snowy'), ('windy', 'images/windy')], max_length=80, null=True)),
            ],
        ),
    ]
