# Generated by Django 3.1.3 on 2021-02-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='create_date',
            new_name='answer_date',
        ),
        migrations.AddField(
            model_name='answers',
            name='cm_answer_date',
            field=models.DateTimeField(null=True),
        ),
    ]
